import Image from 'next/image';
import React from 'react';

const paymentMethods = [
    'BANK DEPOSIT', 'RUPEE-O', 'UPI', 'PhonePe', 'Paytm',
    'IMPS', 'freecharge', 'G Pay', 'Airtel Payments', 'AstroPay',
];

const navLinks = [
    { label: 'Home',              section: 'home' },
    { label: 'Skyexchange Login', section: 'login' },
    { label: 'Sign Up',           section: 'sign-up' },
    { label: 'Skyexchange 247',   section: 'sports-betting' },
    { label: 'Skyexchange agent', section: 'about' },
    { label: 'Skyexchange app',   section: 'apk-guide' },
    { label: 'Skyexchange Art',   section: 'about' },
    { label: 'Skyexchange biz',   section: 'about' },
    { label: 'Skyexchange ID',    section: 'login' },
    { label: 'SkyExchin VIP',     section: 'promotions' },
    { label: 'Skyexchange XYZ',   section: 'about' },
    { label: 'Skyinplay',         section: 'sports-betting' },
    { label: 'About Us',          section: 'about' },
];

const scrollTo = (e, section) => {
    e.preventDefault();
    const el = document.getElementById(section);
    if (!el) return;
    const headerH = document.querySelector('.skyexch-header')?.offsetHeight || 107;
    window.scrollTo({ top: el.offsetTop - headerH, behavior: 'smooth' });
};

const Footer = () => {
    return (
        <footer className="site-footer">

            {/* LOGO STRIP */}
            <div className="ft-logo-strip" data-aos="fade-in">
                <Image
                    src="/images/logo.jpg"
                    alt="Skyexchange Logo"
                    width={280}
                    height={72}
                    style={{ width: '280px', height: '72px', objectFit: 'cover', objectPosition: 'center center', display: 'block' }}
                />
            </div>

            {/* CONTACT BAR */}
            <div className="ft-contact-bar" data-aos="fade-up">
                <a href="tel:+919062813000" className="ft-contact-item ft-contact-link">
                    <span className="ft-contact-icon">📞</span>
                    <span>Customer Support: +91 9062813000</span>
                </a>
                <a href="https://wa.me/9062813000" target="_blank" rel="noopener noreferrer" className="ft-contact-item ft-contact-link">
                    <span className="ft-contact-icon">💬</span>
                    <span>WhatsApp: +91 9062813000</span>
                </a>
                <div className="ft-contact-item">
                    <span className="ft-contact-icon">✉️</span>
                    <span>Email info@skyexchange.com</span>
                </div>
            </div>

            {/* LICENSE BLOCK */}
            <div className="ft-license-row" data-aos="fade-up" data-aos-delay="100">
                <div className="ft-gc-logo">
                    <div className="ft-gc-badge">
                        <span className="ft-gc-text">GC</span>
                    </div>
                    <div className="ft-gc-label">
                        <span className="ft-gc-brand">GAMING</span>
                        <span className="ft-gc-brand">CURACAO</span>
                    </div>
                </div>
                <div className="ft-license-text">
                    <p>
                        Skyexch.art is operated by Sky Infotech N.V. a limited liability company incorporated
                        under the laws of Curacao with company Registration number 152377 with registered office
                        at Abraham de Veerstraat 9, Curacao P.O Box 3421 and is licensed and regulated by the
                        Curacao authority as the regulatory body responsible holding a (Sub-license with License
                        number 365/JAZ Sub-License GLH-OCCHKTW0707072017 granted on 6.07.2017).
                    </p>
                    <p>
                        Players are requested not to contact any untrusted sources for{' '}
                        <span className="ft-highlight">Skyexchange</span> accounts as this is an online site
                        and they can only register independently without any agents. Only deposit through the
                        account details generated by the system or provided by our official support team.
                    </p>
                </div>
            </div>

            {/* PAYMENT METHODS */}
            <div className="ft-payments" data-aos="fade-up" data-aos-delay="200">
                {paymentMethods.map((pm) => (
                    <span key={pm} className="ft-payment-badge">{pm}</span>
                ))}
            </div>

            <hr className="ft-divider" />

            {/* NAV LINKS */}
            <nav className="ft-nav" data-aos="fade-up" data-aos-delay="300">
                {navLinks.map(({ label, section }, i) => (
                    <span key={label} className="ft-nav-item">
                        <a href={`/#${section}`} className="ft-nav-link" onClick={(e) => scrollTo(e, section)}>{label}</a>
                        {i < navLinks.length - 1 && <span className="ft-nav-sep">|</span>}
                    </span>
                ))}
            </nav>
            <nav className="ft-nav ft-nav--sm">
                <span className="ft-nav-item">
                    <a href="/#faq" className="ft-nav-link" onClick={(e) => scrollTo(e, 'faq')}>Blog</a>
                </span>
                <span className="ft-nav-sep">|</span>
                <span className="ft-nav-item">
                    <a href="/#faq" className="ft-nav-link" onClick={(e) => scrollTo(e, 'faq')}>Contact Us</a>
                </span>
            </nav>

            {/* COPYRIGHT */}
            <p className="ft-copy">© 2026 Skyexchangeapp. All rights reserved.</p>

            <style jsx>{`
                .site-footer {
                    background: #ebebeb;
                    padding: 0 0 32px;
                    font-family: 'Poppins', Arial, sans-serif;
                }

                /* LOGO STRIP */
                .ft-logo-strip {
                    background: #111111;
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    padding: 18px 20px;
                }

                /* CONTACT BAR */
                .ft-contact-bar {
                    display: flex;
                    max-width: 1300px;
                    margin: 0 auto;
                    padding: 32px 50px 28px;
                    gap: 16px;
                }
                .ft-contact-item {
                    flex: 1;
                    display: flex;
                    align-items: center;
                    gap: 10px;
                    border: 1px solid #cccccc;
                    border-radius: 6px;
                    padding: 14px 20px;
                    background: #ffffff;
                    color: #333333;
                    font-size: 14px;
                    font-weight: 500;
                }
                .ft-contact-icon { font-size: 1.1rem; flex-shrink: 0; }
                .ft-contact-link { text-decoration: none; color: inherit; }

                /* LICENSE */
                .ft-license-row {
                    display: flex;
                    align-items: flex-start;
                    gap: 28px;
                    max-width: 1300px;
                    margin: 0 auto;
                    padding: 10px 50px 28px;
                }
                .ft-gc-logo {
                    display: flex;
                    align-items: center;
                    gap: 10px;
                    flex-shrink: 0;
                }
                .ft-gc-badge {
                    width: 54px;
                    height: 54px;
                    border-radius: 50%;
                    background: linear-gradient(135deg, #e53935, #1565c0, #4caf50, #ffd600);
                    display: flex;
                    align-items: center;
                    justify-content: center;
                }
                .ft-gc-text {
                    color: #ffffff;
                    font-weight: 900;
                    font-size: 1rem;
                    letter-spacing: 1px;
                }
                .ft-gc-label {
                    display: flex;
                    flex-direction: column;
                }
                .ft-gc-brand {
                    font-size: 0.75rem;
                    font-weight: 700;
                    color: #333333;
                    letter-spacing: 1.5px;
                    line-height: 1.3;
                }
                .ft-license-text p {
                    color: #444444;
                    font-size: 13px;
                    line-height: 1.75;
                    margin-bottom: 8px;
                }
                .ft-license-text p:last-child { margin-bottom: 0; }
                .ft-highlight { color: #E53935; font-weight: 600; }

                /* PAYMENTS */
                .ft-payments {
                    display: flex;
                    flex-wrap: wrap;
                    justify-content: center;
                    gap: 8px;
                    max-width: 1300px;
                    margin: 0 auto;
                    padding: 4px 50px 24px;
                }
                .ft-payment-badge {
                    border: 1px solid #bbbbbb;
                    border-radius: 4px;
                    padding: 6px 14px;
                    font-size: 12px;
                    font-weight: 600;
                    color: #444444;
                    background: #ffffff;
                    letter-spacing: 0.5px;
                }

                /* DIVIDER */
                .ft-divider {
                    border: none;
                    border-top: 1px solid #cccccc;
                    max-width: 1300px;
                    margin: 0 auto 20px;
                }

                /* NAV */
                .ft-nav {
                    display: flex;
                    flex-wrap: wrap;
                    justify-content: center;
                    align-items: center;
                    max-width: 1300px;
                    margin: 0 auto;
                    padding: 0 50px;
                    row-gap: 2px;
                }
                .ft-nav--sm { margin-top: 4px; }
                .ft-nav-item {
                    display: inline-flex;
                    align-items: center;
                }
                .ft-nav-link {
                    color: #1a73e8;
                    font-size: 13px;
                    text-decoration: none;
                    padding: 4px 8px;
                    transition: color 0.2s;
                    white-space: nowrap;
                }
                .ft-nav-link:hover { color: #E53935; text-decoration: underline; }
                .ft-nav-sep {
                    color: #aaaaaa;
                    font-size: 12px;
                    padding: 0 2px;
                    user-select: none;
                }

                /* COPYRIGHT */
                .ft-copy {
                    text-align: center;
                    color: #666666;
                    font-size: 13px;
                    margin: 20px 0 0;
                    padding: 0 20px;
                }

                /* RESPONSIVE */
                @media (max-width: 900px) {
                    .ft-contact-bar { flex-direction: column; padding: 24px 20px 20px; }
                    .ft-license-row { flex-direction: column; padding: 10px 20px 24px; }
                    .ft-payments { padding: 4px 20px 20px; }
                    .ft-nav { padding: 0 20px; }
                }
            `}</style>
        </footer>
    );
};

export default Footer;
